In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [6]:
df.shape

(569, 33)

In [9]:
df.drop(columns =['id', 'Unnamed: 32'], inplace = True)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


Train test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size = 0.2)

Scaling

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [13]:
X_train

array([[ 0.92464763, -0.49496076,  0.88709387, ...,  1.10047988,
         0.39552755, -0.16768496],
       [-0.42134787,  0.38980736, -0.40037687, ..., -0.05295248,
        -1.07440368,  0.04309646],
       [-0.57410539, -0.34108804, -0.57064853, ..., -0.78673178,
         0.25208031, -0.75086571],
       ...,
       [-1.16495995, -0.386769  , -1.14072472, ..., -0.75099378,
         0.00225647, -0.42141379],
       [ 0.62201481,  0.08927471,  0.75354748, ...,  0.97470667,
         0.68564555,  0.41040992],
       [ 1.54144215, -0.07661931,  1.51726594, ...,  1.41184526,
         0.60183369,  0.33864252]])

In [14]:
y_train

,diagnosis
253,M
111,B
394,B
118,M
352,M
...,...
489,M
148,B
338,B
479,M


Label Encoder

In [15]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,

Numpy Arrays to Pytorch Tensors

In [17]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [20]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [33]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    #calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


Important Parameters

In [39]:
learning_rate = 0.1
epochs = 10

Training Pipeline

In [40]:
model = MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  print(y_pred)
# loss calculation
loss = model.loss_function(y_pred, y_train_tensor)
print(loss)
#backward pass
loss.backward()
#parameters update
with torch.no_grad():
  model.weights -= learning_rate * model.weights.grad
  model.bias -= learning_rate * model.bias.grad
# zero gradients
model.weights.grad.zero_()
model.bias.grad.zero_()

#print loss in each epoch
print(f'epoch: {epoch}, loss: {loss}')


tensor([[5.0941e-01],
        [9.7292e-01],
        [8.0651e-02],
        [9.9999e-01],
        [1.0000e+00],
        [8.1970e-04],
        [3.8502e-01],
        [8.8785e-01],
        [4.9510e-01],
        [3.6432e-06],
        [3.3922e-06],
        [1.0000e+00],
        [3.7921e-01],
        [3.3530e-04],
        [9.9959e-01],
        [1.1886e-03],
        [9.8905e-01],
        [8.8500e-05],
        [9.9993e-01],
        [1.3977e-03],
        [1.6020e-01],
        [4.3304e-02],
        [2.2282e-01],
        [5.6818e-02],
        [5.1404e-03],
        [9.9845e-01],
        [1.6219e-01],
        [9.4683e-01],
        [1.4133e-02],
        [9.9922e-01],
        [9.9999e-01],
        [9.9572e-01],
        [9.9998e-01],
        [9.9830e-01],
        [8.7178e-01],
        [9.9590e-01],
        [4.0403e-02],
        [8.5369e-04],
        [9.8433e-01],
        [2.6345e-04],
        [1.0000e+00],
        [9.9998e-01],
        [7.6033e-01],
        [8.1483e-01],
        [9.9952e-01],
        [6

In [41]:
model.bias

tensor([-0.0019], dtype=torch.float64, requires_grad=True)

Evaluation

In [46]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()

print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5280086398124695
