In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


Creating Tensors

In [ ]:
#using empty
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.8396, 0.2372, 0.9356],
        [0.4375, 0.3122, 0.0321]])

In [ ]:
#using seeds
torch.rand(2,3)

tensor([[0.3665, 0.1700, 0.1129],
        [0.8710, 0.8945, 0.0269]])

In [ ]:
#manual_seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#arrange
print(torch.arange(0,10,2))

tensor([0, 2, 4, 6, 8])


In [ ]:
#using linsapce
print(torch.linspace(0,10,10))

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
#using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#using full
torch.full((2,3),4)

tensor([[4, 4, 4],
        [4, 4, 4]])

Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[139714589650304, 139714589650304,               0],
        [              0,               0,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

Matematical Operations

In [ ]:
#addition
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
#subtraction
x -2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
#multiplication
x * 4

tensor([[ 4,  8, 12],
        [16, 20, 24]])

In [ ]:
#division
x /3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [ ]:
#int division
(x * 100) //3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [ ]:
#mod
((x *100) // 3) % 2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [ ]:
#power
x ** 3

tensor([[  1,   8,  27],
        [ 64, 125, 216]])

Element Wise Operations

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
#round
torch.round(torch.tensor([1.2,1.5,1.8]))

tensor([1., 2., 2.])

In [ ]:
#ceil
torch.ceil(c)

tensor([ 1, -2,  3, -4])

In [ ]:
#floor
torch.floor(c)

tensor([ 1, -2,  3, -4])

In [ ]:
#clamp
torch.clamp(c,-1,1)

tensor([ 1, -1,  1, -1])

Reduction Operations

In [ ]:
e = torch.randint(size =(2,3), low =0, high = 10, dtype = torch.float32)
f = torch.randint(size =(2,3), low =0, high = 10, dtype = torch.float32)
e
f


tensor([[7., 6., 9.],
        [6., 3., 1.]])

In [ ]:
#sum
torch.sum(e)

#sum along columns
torch.sum(e, dim = 0)

#sum along rows
torch.sum(e, dim = 1)

tensor([ 5., 12.])

In [ ]:
#mean
torch.mean(e)

tensor(2.8333)

In [ ]:
#mean along col 1
torch.mean(e, dim = 0)

tensor([1.0000, 4.5000, 3.0000])

In [ ]:
#median
torch.median(e)

tensor(2.)

In [ ]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
#product
torch.prod(e)

tensor(0.)

In [ ]:
#standard deviation
torch.std(e)

tensor(2.1370)

In [ ]:
# variance
torch.var(e)

tensor(4.5667)

In [ ]:
#argmax
torch.argmax(e)

tensor(4)

In [ ]:
#argmin
torch.argmin(f)

tensor(5)

In [ ]:
g = torch.randint(size =(3,2), low =0, high = 10, dtype = torch.float32)

In [ ]:
g

tensor([[2., 0.],
        [5., 9.],
        [3., 4.]])

In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[71., 90.],
        [30., 31.]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[7., 6.],
        [6., 3.],
        [9., 1.]])

In [ ]:
h = torch.randint(size= (3,3), low =0, high = 10, dtype = torch.float32)
h

tensor([[9., 6., 2.],
        [0., 6., 2.],
        [7., 9., 7.]])

In [ ]:
k = torch.randint(size= (3,3), low =0, high = 10, dtype = torch.float32)

In [ ]:
k

tensor([[3., 3., 4.],
        [3., 7., 0.],
        [9., 0., 9.]])

In [ ]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.3863],
        [1.0986, 1.9459,   -inf],
        [2.1972,   -inf, 2.1972]])

In [ ]:
torch.exp(k)

tensor([[2.0086e+01, 2.0086e+01, 5.4598e+01],
        [2.0086e+01, 1.0966e+03, 1.0000e+00],
        [8.1031e+03, 1.0000e+00, 8.1031e+03]])

In [ ]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.0000],
        [1.7321, 2.6458, 0.0000],
        [3.0000, 0.0000, 3.0000]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9820],
        [0.9526, 0.9991, 0.5000],
        [0.9999, 0.5000, 0.9999]])

In [ ]:
torch.softmax(k, dim =0)

tensor([[2.4665e-03, 1.7970e-02, 6.6920e-03],
        [2.4665e-03, 9.8114e-01, 1.2257e-04],
        [9.9507e-01, 8.9468e-04, 9.9319e-01]])

In [ ]:
torch.relu(k)

tensor([[3., 3., 4.],
        [3., 7., 0.],
        [9., 0., 9.]])

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
m


tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])

In [ ]:
n

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [ ]:
m + n

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

In [ ]:
m.add_(n)

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

In [ ]:
n

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [ ]:
torch.relu(m)

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

In [ ]:
m.relu_()

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

In [ ]:
m

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

Copying a tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [ ]:
a[0][0] = 0
a

tensor([[0.0000, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [ ]:
b

tensor([[0.0000, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [ ]:
id(a)

139708836986096

In [ ]:
id(b)

139708836986096

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [ ]:
b

tensor([[0.0000, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.2036,  0.2018],
        [ 0.2018,  0.9497,  0.6666]])

Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device = device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [ ]:
s = torch.rand(2,3)
s

tensor([[0.6790, 0.9155, 0.2418],
        [0.1591, 0.7653, 0.2979]])

In [ ]:
t = s.to(device)

In [ ]:
t +5

tensor([[5.6790, 5.9155, 5.2418],
        [5.1591, 5.7653, 5.2979]], device='cuda:0')

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
v = torch.rand(2,3,4)
v

tensor([[[0.8035, 0.3813, 0.7860, 0.1115],
         [0.2477, 0.6524, 0.6057, 0.3725],
         [0.7980, 0.8399, 0.1374, 0.2331]],

        [[0.9578, 0.3313, 0.3227, 0.0162],
         [0.2137, 0.6249, 0.4340, 0.1371],
         [0.5117, 0.1585, 0.0758, 0.2247]]])

In [ ]:
v.permute(2,0,1)

tensor([[[0.8035, 0.2477, 0.7980],
         [0.9578, 0.2137, 0.5117]],

        [[0.3813, 0.6524, 0.8399],
         [0.3313, 0.6249, 0.1585]],

        [[0.7860, 0.6057, 0.1374],
         [0.3227, 0.4340, 0.0758]],

        [[0.1115, 0.3725, 0.2331],
         [0.0162, 0.1371, 0.2247]]])

In [ ]:
v.permute(2,0,1).shape

torch.Size([4, 2, 3])